version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      dockerfile: Dockerfile
    image: ml_django
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /app/start

  postgres:
    image: postgres
    container_name: ml_postgres
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8001:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - type: bind
        source: ./dumps/
        target: /opt/dumps/
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A medialibrary worker -l info & celery -A medialibrary beat -l info"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5555:5555
    depends_on:
      - redis