PHOTO_TYPE_USER_AVATAR = 3
PHOTO_TYPE_POSTER = 6
PHOTO_TYPE_MOVIE_PHOTOS = 9
PHOTO_TYPE_GAME_PHOTOS = 12
PHOTO_TYPE_SERIES_PHOTOS = 18
PHOTO_TYPE_VIDEO_PREVIEW = 21

PHOTO_TYPES = (
    (PHOTO_TYPE_USER_AVATAR, "User Avatar"),
    (PHOTO_TYPE_POSTER, "Poster"),
    (PHOTO_TYPE_MOVIE_PHOTOS, "Movie Photos"),
    (PHOTO_TYPE_GAME_PHOTOS, "Game Photos"),
    (PHOTO_TYPE_SERIES_PHOTOS, "Series Photos"),
    (PHOTO_TYPE_VIDEO_PREVIEW, "Video Preview"),
)

VIDEO_TYPE_TRAILER = 3

VIDEO_TYPES = ((VIDEO_TYPE_TRAILER, "Trailer"),)
