PHOTO_TYPE_USER_AVATAR = 3
PHOTO_TYPE_POSTER = 6
PHOTO_TYPE_MOVIE_PHOTOS = 9
PHOTO_TYPE_GAME_PHOTOS = 12
PHOTO_TYPE_ANIME_PHOTOS = 15
PHOTO_TYPE_SERIES_PHOTOS = 18

PHOTO_TYPES = (
    (PHOTO_TYPE_USER_AVATAR, "User Avatar"),
    (PHOTO_TYPE_POSTER, "Poster"),
    (PHOTO_TYPE_MOVIE_PHOTOS, "Movie Photos"),
    (PHOTO_TYPE_GAME_PHOTOS, "Game Photos"),
    (PHOTO_TYPE_ANIME_PHOTOS, "Anime Photos"),
    (PHOTO_TYPE_SERIES_PHOTOS, "Series Photos"),
)
