STAFF_ROLE_ACTOR = 3
STAFF_ROLE_DIRECTOR = 6
STAFF_ROLE_SCREENWRITER = 9
STAFF_ROLE_PRODUCER = 12
STAFF_ROLE_OPERATOR = 15
STAFF_ROLE_COMPOSER = 18
STAFF_ROLE_PAINTER = 21
STAFF_ROLE_EDITOR = 24

STAFF_ROLES = (
    (STAFF_ROLE_ACTOR, "Actor"),
    (STAFF_ROLE_DIRECTOR, "Director"),
    (STAFF_ROLE_SCREENWRITER, "Screen Writer"),
    (STAFF_ROLE_PRODUCER, "Producer"),
    (STAFF_ROLE_OPERATOR, "Operator"),
    (STAFF_ROLE_COMPOSER, "Composer"),
    (STAFF_ROLE_PAINTER, "Painter"),
    (STAFF_ROLE_EDITOR, "Editor"),
)

SERIES_TYPE_TV = 3
SERIES_TYPE_ANIME = 6

SERIES_TYPES = (
    (SERIES_TYPE_TV, "Television Series"),
    (SERIES_TYPE_ANIME, "Anime Series"),
)
