USER_MEDIA_COLLECTION_STATUS_WATCHED = 3
USER_MEDIA_COLLECTION_STATUS_PLANNED = 6
USER_MEDIA_COLLECTION_STATUS_IN_PROGRESS = 9
USER_MEDIA_COLLECTION_STATUS_ABANDONED = 12

USER_MEDIA_COLLECTION_STATUSES = (
    (USER_MEDIA_COLLECTION_STATUS_WATCHED, "Watched"),
    (USER_MEDIA_COLLECTION_STATUS_IN_PROGRESS, "In Progress"),
    (USER_MEDIA_COLLECTION_STATUS_PLANNED, "Planned"),
    (USER_MEDIA_COLLECTION_STATUS_ABANDONED, "Abandoned"),
)

USER_GAME_COLLECTION_STATUS_PLAYING = 3
USER_GAME_COLLECTION_STATUS_COMPLETED = 6
USER_GAME_COLLECTION_STATUS_ABANDONED = 9
USER_GAME_COLLECTION_STATUS_PLANNED = 12

USER_GAME_COLLECTION_STATUSES = (
    (USER_GAME_COLLECTION_STATUS_COMPLETED, "Completed"),
    (USER_GAME_COLLECTION_STATUS_PLAYING, "Playing"),
    (USER_GAME_COLLECTION_STATUS_PLANNED, "Planned"),
    (USER_GAME_COLLECTION_STATUS_ABANDONED, "Abandoned"),
)
