# Generated by Django 5.2 on 2025-04-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anime_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_developer",
                to="catalog.developer",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(
                related_name="game_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="genres",
            field=models.ManyToManyField(
                related_name="anime_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_country",
                to="common.country",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="movie_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                related_name="movie_actors", to="catalog.person"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                related_name="movie_directors", to="catalog.person"
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="directors",
            field=models.ManyToManyField(
                related_name="anime_directors", to="catalog.person"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="actors",
            field=models.ManyToManyField(
                related_name="series_actors", to="catalog.person"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_country",
                to="common.country",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="directors",
            field=models.ManyToManyField(
                related_name="series_directors", to="catalog.person"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="genres",
            field=models.ManyToManyField(
                related_name="series_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_poster",
                to="common.photo",
            ),
        ),
    ]
