# Generated by Django 5.2 on 2025-04-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(
                related_name="game_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.company",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="movie_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.company",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="genres",
            field=models.ManyToManyField(
                related_name="series_genres", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie",
                to="catalog.movie",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_person",
                to="catalog.person",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series",
                to="catalog.series",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="staff",
            field=models.ManyToManyField(
                related_name="series_staff",
                through="catalog.Staff",
                to="catalog.person",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="staff",
            field=models.ManyToManyField(
                related_name="movie_staff", through="catalog.Staff", to="catalog.person"
            ),
        ),
    ]
