# Generated by Django 5.2 on 2025-04-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="gamerating",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="catalog.game",
            ),
        ),
        migrations.AddField(
            model_name="gamerating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(related_name="games", to="catalog.mediagenre"),
        ),
        migrations.AddField(
            model_name="movie",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.company",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="movies", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="movierating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="catalog.movie",
            ),
        ),
        migrations.AddField(
            model_name="movierating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.company",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="genres",
            field=models.ManyToManyField(
                related_name="series", to="catalog.mediagenre"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_poster",
                to="common.photo",
            ),
        ),
        migrations.AddField(
            model_name="seriesrating",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="catalog.series",
            ),
        ),
        migrations.AddField(
            model_name="seriesrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_staff",
                to="catalog.movie",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_person",
                to="catalog.person",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_staff",
                to="catalog.series",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="staff",
            field=models.ManyToManyField(
                related_name="series", through="catalog.Staff", to="catalog.person"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="staff",
            field=models.ManyToManyField(
                related_name="movies", through="catalog.Staff", to="catalog.person"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamerating",
            unique_together={("game", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="movierating",
            unique_together={("movie", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="seriesrating",
            unique_together={("series", "user")},
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("movie__isnull", False), ("series__isnull", True)),
                    models.Q(("movie__isnull", True), ("series__isnull", False)),
                    _connector="OR",
                ),
                name="exactly_one_of_movie_series_game",
            ),
        ),
    ]
