# Generated by Django 5.2 on 2025-04-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Staff Role",
                "verbose_name_plural": "Staff Roles",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="imdb_id",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="person",
            name="imdb_id",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="imdb_id",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_staff",
                to="catalog.movie",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_staff",
                to="catalog.series",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.staffrole",
            ),
        ),
    ]
